{
  "_annotation": {
    "cve_id": "CVE-2023-45853",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2023/CVE-2023-45853.json",
    "reason": "Adjust CPE configurations to indicate that version 1.3.1 addressing the flaw is published."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:zlib:zlib:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "D9777259-9187-4F85-AF5A-48C12FD65A2F",
                "versionEndExcluding": "1.3.1",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      },
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:minizip_project:minizip:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "CD061B66-F416-5FD6-BBD5-BCF7FE07EA03",
                "versionEndExcluding": "1.3.1",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      },
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:smihica:pyminizip:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "5C7D42DB-C5AE-41AF-A6DB-A9B12E064DDE",
                "versionEndIncluding": "0.2.6",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}