{
  "_annotation": {
    "cna": "github_m",
    "cve_id": "CVE-2024-32481",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-32481.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "references": [
      "https://github.com/vyperlang/vyper/blob/9136169468f317a53b4e7448389aa315f90b95ba/vyper/codegen/stmt.py#L286-L287",
      "https://github.com/vyperlang/vyper/commit/3de1415ee77a9244eb04bdb695e249d3ec9ed868",
      "https://github.com/vyperlang/vyper/commit/5319cfbe14951e007ccdb323257e5ada869b35d5",
      "https://github.com/vyperlang/vyper/security/advisories/GHSA-ppx5-q359-pvwj"
    ]
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:vyperlang:vyper:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "54BD3DA7-343E-50FE-AE7E-3F141E34ECAA",
                "versionEndExcluding": "0.4.0b1",
                "versionStartIncluding": "0.3.8",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}