{
  "_annotation": {
    "cna": "github_m",
    "cve_id": "CVE-2024-32474",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-32474.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD.",
    "references": [
      "https://github.com/getsentry/sentry/commit/d5b34568d9f1c41362ccb62141532a0a2169512f",
      "https://github.com/getsentry/sentry/pull/66393",
      "https://github.com/getsentry/sentry/pull/69148",
      "https://github.com/getsentry/sentry/security/advisories/GHSA-6cjm-4pxw-7xp9"
    ]
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:functional:sentry:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "40BAC563-B31A-5FC0-AA0B-3122863D0F30",
                "versionEndExcluding": "24.4.1",
                "versionStartIncluding": "24.3.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          },
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:sentry:sentry:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "9FD6BBCA-892E-5BD6-852A-B673CBA1204D",
                "versionEndExcluding": "24.4.1",
                "versionStartIncluding": "24.3.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}