{
  "_annotation": {
    "cve_id": "CVE-2025-30214",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2025/CVE-2025-30214.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:frappe:frappe:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "8BCA273C-71B9-5582-8F88-A6F5635368CA",
                "versionEndExcluding": "14.89.0",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:frappe:frappe:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "13246B8D-FF5E-588D-B39F-4605E2C3BCFE",
                "versionEndExcluding": "15.51.0",
                "versionStartIncluding": "15.0.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}