{
  "_annotation": {
    "cve_id": "CVE-2025-30213",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2025/CVE-2025-30213.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:frappe:frappe:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "BADC3271-0E24-5848-A517-21C2EB0EE2FE",
                "versionEndExcluding": "14.91.0",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:frappe:frappe:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "AF4F4900-7549-5829-959E-7A145535CAEB",
                "versionEndExcluding": "15.52.0",
                "versionStartIncluding": "15.0.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}